#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
TOTAL_MINUTES=6

# Racine du repo = parent de tools/, quel que soit le cwd de l'appelant.
REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
LIB_DIR="$REPO_ROOT/lib"

# Dossier Téléchargements de l'utilisateur, pour proposer la copie automatique.
DOWNLOADS="${DOWNLOADS:-$HOME/Downloads}"

# Plancher de taille commun aux deux binaires (les vrais font 117 et 144 Mo).
# Écarte un fichier tronqué ou une page d'erreur HTML renommée en .dll/.exe.
MIN_MB=20

# have_binary CHEMIN — le binaire est-il en place et plausible (≥ MIN_MB) ?
have_binary() {
  local path="$1"
  [[ -f "$path" ]] || return 1
  (( $(wc -c < "$path") / 1000000 >= MIN_MB ))
}

# size_mb CHEMIN — taille en Mo, pour l'affichage.
size_mb() { printf '%s' "$(( $(wc -c < "$1") / 1000000 ))"; }

# clean_path "..." — ôte guillemets encadrants et CR final (chemin collé depuis
# l'explorateur ou un contexte CRLF : sans ça, [[ -f ]] échoue sur un chemin valide).
clean_path() {
  local p="$1"
  p="${p%$'\r'}"; p="${p%\"}"; p="${p#\"}"
  printf '%s' "$p"
}

# place_binary SRC DEST NOM — copie SRC vers DEST, sauf si c'est déjà le même
# fichier (cp échouerait, et `set -e` tuerait le wizard en plein milieu).
place_binary() {
  local src="$1" dest="$2" name="$3"
  mkdir -p "$LIB_DIR"
  if [[ "$src" -ef "$dest" ]]; then
    printf '  %s✓ déjà au bon endroit%s lib/%s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  cp -- "$src" "$dest"
  printf '  %s✓ copié%s → lib/%s (%s Mo)\n' "$GREEN" "$RESET" "$name" "$(size_mb "$dest")"
}

# collect_binary NOM_FICHIER DEST — s'assure que DEST existe.
# Cherche d'abord le fichier dans ~/Downloads (et ses sous-dossiers d'archive
# extraite), propose la copie ; sinon demande le chemin à la main. Idempotent :
# ne fait rien si le binaire est déjà en place.
collect_binary() {
  local name="$1" dest="$2" found src

  if have_binary "$dest"; then
    printf '  %s✓ déjà en place%s lib/%s (%s Mo)\n' \
      "$GREEN" "$RESET" "$name" "$(size_mb "$dest")"
    return 0
  fi

  # Candidat le plus récemment modifié sous ~/Downloads (profondeur 3 : couvre
  # Downloads/mpv-dev-x86_64-.../ après extraction). Trié par mtime décroissant
  # pour tomber sur le dernier build téléchargé quand il y en a plusieurs.
  if [[ -d "$DOWNLOADS" ]]; then
    found=$(find "$DOWNLOADS" -maxdepth 3 -name "$name" -type f -printf '%T@\t%p\n' \
            2>/dev/null | sort -rn | head -n1 | cut -f2-) || true
    if [[ -n "${found:-}" ]] && have_binary "$found"; then
      say "Trouvé : $found"
      note "  (modifié le $(date -r "$found" '+%d/%m/%Y %H:%M' 2>/dev/null || echo '?'))"
      if confirm "Copier ce fichier vers lib/$name ?"; then
        place_binary "$found" "$dest" "$name"
        return 0
      fi
    fi
  fi

  # Saisie manuelle du chemin, avec re-demande tant que ce n'est pas bon.
  while true; do
    printf '  %sChemin complet du %s extrait :%s ' "$BOLD" "$name" "$RESET"
    read -r src || true
    src=$(clean_path "$src")
    if [[ -z "$src" ]]; then
      SKIPPED+=("lib/$name — à copier à la main dans $LIB_DIR")
      warn "$name non fourni — l'app ne pourra pas s'en servir"
      return 1
    fi
    if have_binary "$src"; then
      place_binary "$src" "$dest" "$name"
      return 0
    fi
    warn "introuvable ou trop petit (< ${MIN_MB} Mo attendu) : $src"
    note "Laisse vide et Entrée pour passer cette étape."
  done
}

# ffmpeg_version CHEMIN — imprime la version lue dans la bannière, ou rien si le
# binaire ne s'exécute pas (fichier bloqué par Windows, archive tronquée).
# On capture la sortie AVANT de la filtrer : dans un pipe, le statut serait celui
# du dernier maillon, jamais celui de ffmpeg.
# Deux formes existent : une release numérotée ("ffmpeg version 7.1.1") et un
# build git master ("ffmpeg version N-125658-g0869e710e6-20260718"), que les
# builds gyan.dev « git » et les mpv-dev de shinchiro utilisent couramment.
ffmpeg_version() {
  local out
  out=$("$1" -version 2>/dev/null) || return 1
  printf '%s' "$out" | head -n1 | awk '{print $3}'
}

# version_ok VERSION — la version satisfait-elle le minimum 7.1 ?
# Un build git master (N-…) est plus récent que n'importe quelle release : accepté.
version_ok() {
  local v="$1" maj min
  [[ -z "$v" ]] && return 1
  [[ "$v" == N-* ]] && return 0
  [[ "$v" =~ ^([0-9]+)\.([0-9]+) ]] || return 1
  maj="${BASH_REMATCH[1]}"; min="${BASH_REMATCH[2]}"
  (( maj > 7 )) && return 0
  (( maj < 7 )) && return 1
  (( min >= 1 ))
}

banner "Wallflow — binaires de dev (libmpv + ffmpeg)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prérequis" 1
say "Deux binaires natifs sont exclus du dépôt (trop lourds pour git) et"
say "doivent être posés dans lib/ : libmpv-2.dll et ffmpeg.exe."
say ""

if command -v dotnet >/dev/null 2>&1; then
  printf '  %s✓%s dotnet : %s\n' "$GREEN" "$RESET" "$(dotnet --version 2>/dev/null || echo '?')"
else
  warn "dotnet introuvable dans le PATH — installe le .NET SDK avant de builder."
  SKIPPED+=(".NET SDK (https://dotnet.microsoft.com/download)")
fi
note "Il te faudra aussi de quoi ouvrir des .7z (7-Zip : https://www.7-zip.org)."
pause "Prêt ?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "libmpv-2.dll" 2
say "Build Windows de libmpv par shinchiro (celui que Wallflow attend)."
open_url "https://github.com/shinchiro/mpv-winbuild-cmake/releases/latest"
step "Dans les Assets de la release, prends le fichier nommé"
note "    mpv-dev-x86_64-<date>-git-<hash>.7z"
note "  ('dev' — pas mpv-x86_64 tout court : c'est celui qui contient la DLL)"
step "Extrais l'archive (clic droit → 7-Zip → Extraire ici)."
step "La DLL est à la racine de l'archive : libmpv-2.dll (~100-120 Mo)."
note "Si ton build la nomme mpv-2.dll, le code accepte les deux noms, mais"
note "garde libmpv-2.dll comme destination (c'est ce que copie le .csproj)."
say ""
collect_binary "libmpv-2.dll" "$LIB_DIR/libmpv-2.dll" || true

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "ffmpeg.exe" 2
say "ffmpeg ≥ 7.1 requis : c'est la version qui décode le WebP animé."
note "Un ffmpeg déjà présent dans le PATH suffit à l'app (WallpaperCache le"
note "cherche aussi là), mais le poser dans lib/ garantit la bonne version."
open_url "https://www.gyan.dev/ffmpeg/builds/"
step "Section 'release builds' → télécharge ffmpeg-release-full.7z"
step "Extrais l'archive, puis ouvre le sous-dossier bin/."
step "Le binaire à récupérer est bin/ffmpeg.exe (et lui seul)."
say ""
if collect_binary "ffmpeg.exe" "$LIB_DIR/ffmpeg.exe"; then
  FFMPEG_V=$(ffmpeg_version "$LIB_DIR/ffmpeg.exe" || true)
  if [[ -z "${FFMPEG_V:-}" ]]; then
    warn "impossible de lire la version — fichier bloqué par Windows ?"
    note "Clic droit sur ffmpeg.exe → Propriétés → cocher 'Débloquer'."
    SKIPPED+=("vérifier que lib/ffmpeg.exe s'exécute et est en ≥ 7.1")
  elif version_ok "$FFMPEG_V"; then
    printf '  %s✓ ffmpeg %s%s (≥ 7.1)\n' "$GREEN" "$FFMPEG_V" "$RESET"
  else
    warn "ffmpeg $FFMPEG_V < 7.1 — le WebP animé ne sera pas décodé."
    note "Reprends un build 'release full' plus récent sur gyan.dev."
    SKIPPED+=("remplacer lib/ffmpeg.exe par une version ≥ 7.1 (actuelle : $FFMPEG_V)")
  fi
fi
pause "Continuer vers la vérification ?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vérification" 1
say "État de lib/ :"
BINARIES_OK=1
for f in libmpv-2.dll ffmpeg.exe; do
  if have_binary "$LIB_DIR/$f"; then
    printf '  %s✓%s lib/%-16s %s Mo\n' "$GREEN" "$RESET" "$f" "$(size_mb "$LIB_DIR/$f")"
  else
    printf '  %s✗%s lib/%-16s manquant\n' "$RED" "$RESET" "$f"
    BINARIES_OK=0
  fi
done

if (( BINARIES_OK == 0 )); then
  say ""
  warn "Un binaire manque : le build restera vert (le .csproj les copie sous"
  note "condition d'existence) mais l'app ne pourra pas lire de wallpaper."
fi

say ""
if command -v dotnet >/dev/null 2>&1 && confirm "Lancer 'dotnet build' pour valider ?"; then
  say "Build en cours…"
  if (cd "$REPO_ROOT" && dotnet build -v quiet --nologo); then
    printf '  %s✓ build vert%s\n' "$GREEN" "$RESET"
  else
    warn "le build a échoué — la sortie ci-dessus dit pourquoi"
    SKIPPED+=("dotnet build en échec — à corriger")
  fi
else
  SKIPPED+=("vérifier le build : dotnet build")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
